#!/bin/bash
#set_vms_ctlips.sh
ipnum=$(ip a|grep '10.2.7'|awk '{print$2}'|cut -d'.' -f4|cut -d'/' -f1)
cat >/etc/sysconfig/network-scripts/ifcfg-eth1 <<EOF
# Generated by parse-kickstart
DEVICE="eth1"
IPV6INIT="no"
BOOTPROTO="static"
ONBOOT="yes"
IPADDR=192.168.11.${ipnum}
NETMASK=255.255.252.0
EOF

ifdown eth1
ifup eth1
##
sleep 3
##
ping -w 3 192.168.11.${ipnum}


#curl -O http://10.2.4.251/set_vms_ctlips.sh
#sh set_vms_ctlips.sh
